// Rent It Terms of Service, as data for components/LegalDocument.jsx.
//
// Written for what this Platform actually does: a peer-to-peer marketplace
// in India where people rent out equipment (farming, construction, DIY,
// events, moving, medical), bargain over price in chat, share photos,
// documents and locations, and pay each other directly - Rent It never
// handles money. It tries to cover the real risks of that model (injury
// from heavy machinery, vehicles on public roads, medical devices, off-
// platform payment fraud, meeting strangers, deposits nobody holds in
// escrow, intermediary obligations under the IT Act) as fully as possible.
//
// It is a detailed starting point, NOT legal advice: have it reviewed by a
// lawyer qualified in Indian law before relying on it, fill in the company
// details in content/legal.js, and bump TERMS_VERSION when it changes
// materially so users are asked to accept again.

export const TERMS_SECTIONS = [
  {
    id: 'introduction',
    title: 'Introduction and your agreement',
    body: [
      'These Terms of Service ("Terms") are a legally binding agreement between you and {{legalName}}, a {{entityType}} with its registered office at {{address}} ("Rent It", "we", "us" or "our"). They govern your access to and use of the Rent It website at {{website}}, any related applications, and every feature, service, message and tool we provide (together, the "Platform").',
      'By ticking the acceptance boxes and clicking "I agree" when you open the Platform, by creating an account, or by otherwise accessing or using the Platform in any way, you confirm that you have read, understood and agree to be bound by these Terms and by our Privacy Policy, which forms part of these Terms. If you do not agree to every part of these Terms, you must not access or use the Platform.',
      'These Terms are an electronic record under the Information Technology Act, 2000 and the rules made under it, and are published in accordance with Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 ("IT Rules"). They are generated by a computer system and do not require a physical or digital signature. Under section 10A of the Information Technology Act, 2000, a contract formed by electronic means is valid and enforceable.',
      'Visitors who do not have an account are asked to accept these Terms each time they newly open the Platform. Account holders accept once per version of these Terms, and we keep a record of when, which version, and from which browser you accepted. If these Terms change materially, you will be asked to accept the new version before continuing.',
      { callout: 'Please read these Terms carefully. They limit our liability, require you to take responsibility for the equipment you rent or rent out and for your own safety, explain that all payments happen directly between users without our involvement, and contain an arbitration clause that affects how disputes with us are resolved.' },
    ],
  },
  {
    id: 'definitions',
    title: 'Definitions',
    body: [
      'In these Terms, unless the context requires otherwise:',
      {
        list: [
          '"User" or "you" means any person who accesses or uses the Platform, whether or not they have an account, including Owners and Renters.',
          '"Owner" means a User who lists an Item for rent on the Platform.',
          '"Renter" means a User who requests, negotiates for or rents an Item through the Platform.',
          '"Item" means any equipment, tool, machine, device, vehicle, structure, accessory or other goods listed on the Platform, together with anything supplied with it (manuals, keys, chargers, attachments, fuel, safety gear).',
          '"Listing" means an Owner\'s advertisement for an Item, including its photos, description, condition, price, deposit, cancellation policy, delivery options and any other terms.',
          '"Request" means a Renter\'s request to rent an Item for specific dates at an offered daily price.',
          '"Offer" means the dates and daily price proposed in a Request or in any counter-offer, and "Deal" means an Offer that has been accepted through the Platform.',
          '"Rental" means the arrangement between an Owner and a Renter for an Item, from the moment a Deal is formed until the Item is returned and the Rental is marked complete, cancelled or resolved.',
          '"Deposit" means any refundable security amount an Owner requires in connection with a Rental.',
          '"Content" means anything you post, upload, send or share on the Platform, including Listings, photos, messages, documents, locations, reviews and profile information.',
          '"Chat" means the Platform\'s messaging feature, including text messages, Offer cards, status messages, photos, documents and locations sent through it.',
          '"Staff" means the people who administer and moderate the Platform on our behalf.',
          '"Applicable Law" means all laws, rules, regulations, orders, notifications and binding guidelines in force in India (and any other jurisdiction that applies to you or to a Rental).',
        ],
      },
    ],
  },
  {
    id: 'who-we-are',
    title: 'What Rent It is - and what it is not',
    body: [
      'Rent It is an online marketplace. We provide a technology platform where Owners can list Items, Renters can find them, and the two can communicate, negotiate and record the terms they agree. We act as an "intermediary" within the meaning of section 2(1)(w) of the Information Technology Act, 2000, and as a "marketplace e-commerce entity" for the purposes of the Consumer Protection (E-Commerce) Rules, 2020, to the extent those Rules apply.',
      'Rent It is NOT:',
      {
        list: [
          'the owner, supplier, lessor, lessee, seller, buyer, manufacturer, importer, repairer or insurer of any Item;',
          'a party to any Rental, Deal, rental agreement, deposit arrangement or payment between an Owner and a Renter;',
          'an agent, broker, employee, partner, representative or guarantor of any User;',
          'a payment service, payment aggregator, escrow agent or bank - we never collect, hold, transfer or refund money for a Rental;',
          'a transport, delivery, logistics, installation, operation or training service;',
          'an inspector, certifier, tester or surveyor of Items, their safety, their condition, their fitness for any purpose, or their compliance with law.',
        ],
      },
      'Every Rental is a contract made directly and only between the Owner and the Renter. We do not control, and are not responsible for, the existence, quality, safety, legality or condition of any Item; the truth or accuracy of any Listing or Content; the ability of an Owner to rent out an Item or of a Renter to pay for or safely use it; or the conduct of any User on or off the Platform.',
    ],
  },
  {
    id: 'eligibility',
    title: 'Who can use Rent It',
    body: [
      'To use the Platform you must:',
      {
        list: [
          'be at least 18 years old and competent to contract under section 11 of the Indian Contract Act, 1872 (of the age of majority, of sound mind, and not disqualified from contracting by any law);',
          'not have been previously suspended or removed from the Platform, and not be prohibited from using it under Applicable Law;',
          'use the Platform only for lawful purposes and in accordance with these Terms;',
          'if you use the Platform on behalf of a business or organisation, have the authority to bind it to these Terms - in which case "you" includes that business or organisation.',
        ],
      },
      'The Platform is not intended for anyone under 18. If you are under 18 you may not create an account, rent, list, operate or take possession of any Item, even with a parent\'s or guardian\'s consent. If we learn that a User is under 18, we will close the account.',
      'By accepting these Terms you represent and warrant that you meet all of these requirements. We may, but are not obliged to, ask for proof.',
    ],
  },
  {
    id: 'accounts',
    title: 'Your account and its security',
    body: [
      'Some features require an account. When you create one you agree to:',
      {
        list: [
          'provide true, accurate, current and complete information, and keep it up to date;',
          'use your own real name and identity - no impersonation, false identities or accounts created on someone else\'s behalf without their authority;',
          'keep only one personal account, and never create a new account after we have suspended or closed one of yours;',
          'keep your password and login methods secret and secure, and not share, sell, rent or transfer your account to anyone;',
          'be responsible for everything that happens under your account, whether or not you authorised it, until you tell us it has been compromised;',
          'notify us immediately at {{supportEmail}} if you believe someone else has accessed your account.',
        ],
      },
      'We may refuse to open an account, or suspend or close one, at our discretion - including where we suspect false information, fraud, a security risk or a breach of these Terms.',
    ],
  },
  {
    id: 'verification',
    title: 'Seller verification (KYC) and its limits',
    body: [
      'Before listing an Item, an Owner must complete our seller verification by submitting a photo of a government-issued identity document and, where asked, a proof of address and contact details. Verification may be carried out by Staff manually and/or through a third-party identity-verification provider.',
      {
        list: [
          'Aadhaar is entirely optional. You may use a PAN card, driving licence, voter ID, passport or another document we accept instead. If you choose to submit Aadhaar, we strongly recommend a masked Aadhaar (with only the last four digits visible), which you can download from UIDAI.',
          'You must submit only your own genuine, valid, unaltered documents. Submitting forged, altered, borrowed or someone else\'s documents is a criminal offence and will result in immediate termination and may be reported to law enforcement.',
          'We may approve, reject or revoke verification at any time, including if new information comes to light.',
        ],
      },
      'Verification is a limited fraud-prevention step. A "verified" status only means that, at the time of review, the documents submitted appeared to match the details provided. It does NOT mean that we vouch for the User\'s honesty, identity, solvency, skill, conduct or ownership of any Item, and it is not a guarantee, endorsement, background check or police verification. You must still take your own precautions with every User, verified or not.',
    ],
  },
  {
    id: 'listings',
    title: 'Listings and the Owner\'s responsibilities',
    body: [
      'If you are an Owner, you are solely responsible for every Listing you publish and every Item you rent out. For each Listing and Item you represent, warrant and undertake that:',
      {
        list: [
          'you are the lawful owner of the Item, or you have every right, permission and authority needed to rent it out - including the consent of any co-owner, employer, financier or lessor;',
          'the Item is not stolen, counterfeit, seized, subject to a court order, or subject to any hypothecation, lien, loan, lease or hire-purchase agreement that forbids renting it out - and if it is financed or hypothecated, you have disclosed that in the Listing and have the financier\'s permission;',
          'the photos are genuine photos of the actual Item and its current condition, and the description, condition, specifications, accessories, age and usage history are accurate and not misleading;',
          'you have disclosed every known defect, damage, wear, missing part, safety issue, manufacturer recall or limitation of the Item;',
          'the Item is safe, in good working order, properly maintained and serviced, fit for its ordinary purpose, and complies with Applicable Law, including any certification, registration, licensing, calibration, insurance or pollution-control requirements;',
          'the price, deposit, minimum rental period, cancellation policy, delivery options and any other terms you state are the terms you will honour;',
          'you will keep the Listing\'s availability accurate and remove or pause it when the Item is not available.',
        ],
      },
      'Prices on the Platform are shown in Indian Rupees. Unless an Owner clearly states otherwise, a listed or agreed price is the full amount the Renter pays the Owner for the Rental (excluding any Deposit). Owners are responsible for any taxes that apply to their rental income or to the Rental (see "Taxes and your own legal compliance").',
      'We may review, refuse, edit for formatting, hide, suspend or remove any Listing at any time and without notice, for example if it appears inaccurate, unsafe, unlawful, fraudulent, duplicated, or in breach of these Terms. We are not obliged to review Listings before they are published.',
    ],
  },
  {
    id: 'prohibited-items',
    title: 'Items you must never list or rent',
    body: [
      'You must not list, offer, request, rent, deliver or use through the Platform any of the following:',
      {
        list: [
          'anything illegal to own, possess, sell, rent, transport or use in India or in the place where the Rental happens;',
          'firearms, ammunition, parts of weapons, explosives, fireworks, or anything regulated under the Arms Act, 1959 or the Explosives Act, 1884;',
          'compressed-gas cylinders (including LPG, oxygen, nitrogen and acetylene cylinders) unless they, their valves and their handling fully comply with the Gas Cylinders Rules, 2016 and any other Applicable Law;',
          'hazardous, toxic, flammable, corrosive or radioactive substances, fuels in unsafe containers, and pesticides, insecticides or other chemicals regulated under the Insecticides Act, 1968 (equipment such as sprayers may be listed only if clean and free of chemical residue);',
          'drones and unmanned aircraft, unless the drone and every User operating it comply with the Drone Rules, 2021 (including registration and pilot certification where required);',
          'motor vehicles for self-drive hire (cars, jeeps, motorcycles, scooters, goods carriers and similar), unless the Owner holds every licence and permit required to rent them out under the Motor Vehicles Act, 1988 and applicable rent-a-cab or rent-a-motorcycle schemes, and the vehicle is registered, insured and has a valid pollution certificate;',
          'stolen, counterfeit, pirated, replica or unlawfully imported goods, or goods that infringe anyone\'s intellectual property;',
          'Items subject to a recall or a safety notice that has not been fully remedied, or Items the Owner knows or ought to know are unsafe;',
          'medical devices or equipment that may only be supplied, rented or used under a licence, prescription or professional supervision, unless every legal requirement is met (see "Medical and mobility equipment");',
          'surveillance, spying, interception or signal-jamming equipment, and anything designed to be used to commit a crime, invade privacy, or evade law enforcement;',
          'animals, wildlife or wildlife products (including anything covered by the Wild Life (Protection) Act, 1972), plants or seeds that are regulated or prohibited;',
          'alcohol, tobacco, drugs, narcotic or psychotropic substances, or related paraphernalia;',
          'real estate, rooms, land or accommodation (the Platform is for movable equipment only), and people or services (such as operators, drivers or labour) offered on their own;',
          'anything else we tell you is not allowed, or that we reasonably consider unsafe, offensive or inappropriate for the Platform.',
        ],
      },
      'We may remove any such Listing, cancel related Rentals on the Platform, suspend the accounts involved, preserve the relevant records, and report the matter to the authorities.',
    ],
  },
  {
    id: 'offers-and-deals',
    title: 'Requests, bargaining and forming a Deal',
    body: [
      'A Renter starts a Rental by sending a Request, which states the rental dates and the daily price the Renter is willing to pay. That price may be the Owner\'s listed price or a different amount. The Request appears in the Chat between the two Users as an Offer card, and the Owner is notified.',
      'Only one Offer is open on a Request at a time. The User who did not make the open Offer may accept it, decline it (which ends the Request), or send a counter-offer with a different price and/or dates, which replaces the open Offer and passes the turn back. A Renter may withdraw a Request, and an Owner may decline one, at any time before a Deal is formed.',
      { heading: 'When a Deal becomes binding' },
      'When one User accepts the other User\'s open Offer through the Platform, a Deal is formed. At that moment, the Owner and the Renter enter into a legally binding rental agreement with each other on: (a) the accepted dates and daily price, and the total they produce; (b) the Deposit, minimum rental period, cancellation policy, delivery options and other terms shown on the Listing at that time; and (c) anything else the two of them expressly agree in the Chat that does not conflict with these Terms or Applicable Law. Accepting an Offer is an acceptance under the Indian Contract Act, 1872 - do not accept unless you intend to honour it.',
      'The record of the Offers, counter-offers and the accepted Deal kept on the Platform is evidence of what was agreed and may be relied on by Staff when reviewing a dispute. You agree not to dispute the authenticity of that record merely because it is electronic.',
      'We may cancel or close a Request, Offer or Rental on the Platform where it breaches these Terms, the Item becomes unavailable, dates overlap an existing booking, or we suspect fraud. Rent It is not responsible if a User does not honour a Deal, but we may take action against that User\'s account.',
    ],
  },
  {
    id: 'payments',
    title: 'Payments happen directly between Users',
    body: [
      { callout: 'Rent It does not process, collect, hold, transfer, guarantee or refund any payment for a Rental. The Renter pays the Owner directly, by a method the two of them choose. Rent It will never ask you to pay us, or anyone else, for a Rental through the Chat or otherwise.' },
      'By agreeing a Deal, the Renter agrees to pay the Owner the agreed amount at the agreed time, and the Owner agrees to provide the Item on the agreed terms. Because payments do not pass through the Platform:',
      {
        list: [
          'we cannot see, confirm, reverse, refund, charge back or recover any payment, and we are not liable if a payment is not made, is made late, is made to the wrong person, is reversed, or is lost to fraud;',
          'you are solely responsible for choosing a safe payment method, checking that a payment has actually arrived in your own bank account or wallet before handing over an Item, and keeping your own receipts and records;',
          'any dispute about money is between the Owner and the Renter (see "Disputes between Users");',
          'we strongly recommend paying only in person at pickup, after inspecting the Item, and never paying in advance to someone you have not met.',
        ],
      },
      { heading: 'Payment scams to watch for' },
      {
        list: [
          'UPI "collect requests" or QR codes you are told to scan or approve in order to receive money - approving a request or entering your UPI PIN always sends money out of your account, never in.',
          'Fake payment screenshots or fake SMS "credit" messages - always confirm in your own banking app.',
          'Overpayment scams, where someone "accidentally" pays too much and asks you to refund the difference.',
          'Requests to pay a "booking fee", "platform charge", "insurance" or "refundable token" to hold an Item, especially to a third party.',
          'Anyone claiming to be Rent It Staff and asking for money, OTPs, passwords or card details.',
        ],
      },
      'If you are a victim of online financial fraud, report it immediately to the National Cyber Crime Helpline on 1930 and at cybercrime.gov.in, and inform your bank, as well as reporting the User to us.',
    ],
  },
  {
    id: 'fees',
    title: 'Fees',
    body: [
      'At present, Rent It does not charge Users any fee to browse, list, send Offers, chat or rent. If we introduce fees in future, we will tell you clearly in advance, update these Terms, and ask you to accept them before any fee applies to you. Fees will never apply retrospectively to Deals formed before they were introduced.',
      'We do not charge Owners to be shown higher in results, and we do not accept payment to remove or alter reviews.',
    ],
  },
  {
    id: 'deposits',
    title: 'Security deposits',
    body: [
      'An Owner may require a refundable Deposit, shown on the Listing. Because Rent It does not handle money, any Deposit is paid by the Renter directly to the Owner, usually at pickup, and is held by the Owner - not by Rent It.',
      {
        list: [
          'The Owner must return the Deposit in full, promptly after the Item is returned, unless the Item was damaged, lost, returned incomplete, returned late or otherwise not as agreed.',
          'Any deduction must be reasonable, limited to the actual cost of the loss or damage (or other amount expressly agreed in the Deal), and supported by evidence such as the pickup and return condition photos, repair quotes or receipts, which the Owner must share with the Renter on request.',
          'Owners must not treat a Deposit as a fee, withhold it without a genuine reason, or use it to pressure a Renter.',
          'Rent It does not hold, guarantee, refund or enforce any Deposit and is not liable for its return. A dispute about a Deposit is a dispute between Users.',
        ],
      },
    ],
  },
  {
    id: 'cancellations',
    title: 'Cancellations, no-shows and late returns',
    body: [
      'Each Listing shows the Owner\'s cancellation policy (for example Free, Flexible or Strict). The Owner and Renter are bound by the policy shown when the Deal was formed and by anything else they expressly agree in the Chat. Rent It does not collect or refund cancellation charges; Users settle them directly.',
      {
        list: [
          'Either User can cancel a confirmed Rental on the Platform, but cancelling on the Platform does not by itself cancel any money owed under the Deal or the cancellation policy.',
          'Failing to turn up for a pickup or return without notice, repeatedly cancelling at the last minute, or keeping an Item beyond the agreed period without the Owner\'s agreement may lead to action against your account.',
          'A Renter who returns an Item late must pay any late charges agreed in the Deal, or otherwise a reasonable amount for the extra time, and is responsible for the Item until it is returned.',
          'Keeping an Item without the Owner\'s permission after the Rental ends may amount to a criminal offence under Applicable Law, including the Bharatiya Nyaya Sanhita, 2023.',
        ],
      },
    ],
  },
  {
    id: 'handover',
    title: 'Handover, inspection and return',
    body: [
      'The Owner and the Renter are responsible for arranging pickup, delivery, handover and return themselves. At handover both Users should:',
      {
        list: [
          'inspect the Item together and check that it matches the Listing and works safely;',
          'record its condition, and any existing damage, with dated photos - the Platform lets you upload pickup and return condition photos to the Rental, and you can also send photos in the Chat;',
          'check and note accessories, attachments, keys, manuals, chargers, fuel or charge level, hour-meter readings and safety equipment;',
          'confirm the agreed return time and place.',
        ],
      },
      'The Owner must give the Renter all instructions, manuals and safety information needed to use the Item safely, and must point out any hazards. The Renter must return the Item on time, clean, in the same condition (apart from fair wear and tear), with everything that came with it, and with any agreed fuel or charge level.',
      'Transporting, loading, unloading, installing and removing an Item are done entirely at the risk of the Users who do them. Heavy or bulky Items must be moved with suitable vehicles, equipment and people.',
    ],
  },
  {
    id: 'safety',
    title: 'Safe use of equipment - assumption of risk',
    body: [
      { callout: 'Many Items on the Platform - including tractors, tillers, excavators, cement mixers, generators, chainsaws, power tools, ladders, scaffolding and electrical equipment - can cause serious injury, permanent disability, death, fire, electrocution and damage to property if used incorrectly, by an untrained person, or if they are faulty. You use every Item entirely at your own risk.' },
      'If you rent an Item, you represent and agree that:',
      {
        list: [
          'you (and anyone you allow to use it) are properly trained, experienced, physically fit and, where the law requires, licensed or certified to operate it;',
          'you will read and follow the manufacturer\'s instructions, the Owner\'s instructions and all safety warnings;',
          'you will use appropriate personal protective equipment (such as helmets, eye and ear protection, gloves, safety boots and harnesses);',
          'you will not operate any Item while under the influence of alcohol, drugs or medication that affects your ability, or while tired or unwell;',
          'you will not allow any child, untrained or unauthorised person to use it, and will keep bystanders, children and animals at a safe distance;',
          'you will use it only for its intended purpose, within its rated capacity, and in suitable conditions (never in rain, near water or in explosive atmospheres unless it is designed for that);',
          'you will stop using it immediately and tell the Owner if it appears faulty, damaged or unsafe, and you will not attempt repairs you are not qualified to make;',
          'you are responsible for the safety of your worksite, including checking for underground cables and pipes before digging, and for complying with any permits the work needs.',
        ],
      },
      'If you are an Owner, you must provide Items that are safe and properly maintained, disclose all hazards and defects, and never rent an Item you know or suspect is unsafe. You must not rent an Item to a person you know or ought reasonably to suspect is untrained, underage, intoxicated or otherwise unfit to use it safely.',
      'To the maximum extent permitted by Applicable Law, you voluntarily assume all risks of injury, illness, death, loss and damage arising from renting, renting out, transporting, operating or being near any Item, and you agree that Rent It is not responsible for them.',
    ],
  },
  {
    id: 'vehicles',
    title: 'Tractors, trailers and anything used on public roads',
    body: [
      'Some Items, such as tractors, trailers and self-propelled machinery, may be "motor vehicles" under the Motor Vehicles Act, 1988 when driven on public roads. Where they are:',
      {
        list: [
          'the Owner must ensure the vehicle is validly registered, has valid third-party insurance as required by section 146 of that Act, a valid pollution-under-control certificate and any other documents the law requires, and must hand over copies with the vehicle;',
          'the person driving it must hold a valid driving licence of the right class under section 3 of that Act;',
          'the vehicle must be used only as its registration permits (for example, a tractor registered for agricultural use must not be used as a commercial goods carrier without the necessary permit);',
          'the User responsible for an offence, challan, fine, toll, accident or third-party claim arising during the Rental must bear it, and must promptly inform the other User and the police where required.',
        ],
      },
      'Rent It does not arrange, check or provide any registration, permit, licence, insurance or road-worthiness certificate.',
    ],
  },
  {
    id: 'medical',
    title: 'Medical and mobility equipment',
    body: [
      'The Platform allows listing of some home-care and mobility Items (such as wheelchairs, walkers, commodes and hospital beds). Such Items may be "medical devices" regulated under the Medical Devices Rules, 2017, and are often used by people who are ill, elderly or vulnerable. If you list or rent them:',
      {
        list: [
          'Nothing on the Platform - including Listings, the Chat and our support assistant - is medical advice. Consult a qualified doctor or therapist about whether an Item is suitable, how to use it safely, and what size or type is needed.',
          'Owners must clean and disinfect Items thoroughly before every Rental, disclose their age, condition and any repairs, and must not list devices that require a licence, prescription or professional supervision to supply or use unless every legal requirement is met.',
          'Items must not be relied on for life-supporting, life-sustaining or critical care without the supervision of a qualified healthcare professional and a backup plan.',
          'Rent It does not verify the certification, calibration, sterility, suitability or safety of any medical or mobility Item.',
        ],
      },
    ],
  },
  {
    id: 'events-construction-farming',
    title: 'Category-specific rules: events, construction, moving and farming',
    body: [
      { heading: 'Events equipment' },
      {
        list: [
          'Generators must be used in the open with adequate ventilation (exhaust fumes can kill), refuelled only when switched off and cool, and must meet the noise and emission limits for diesel generator sets under the Environment (Protection) Rules, 1986.',
          'Sound systems must be used within the limits and hours set by the Noise Pollution (Regulation and Control) Rules, 2000 and any local order, including the restrictions on loudspeakers at night.',
          'Tents, stages, pandals and temporary structures must be erected by competent people, anchored properly, and used with any permission, fire-safety clearance or electrical inspection the local authority requires.',
        ],
      },
      { heading: 'Construction equipment and site work' },
      {
        list: [
          'Users are responsible for building permissions, site safety, and compliance with occupational safety laws that apply to their work (including, where applicable, the Occupational Safety, Health and Working Conditions Code, 2020 and related rules for building and construction work).',
          'Scaffolding, ladders and working-at-height equipment must be inspected before each use, erected on firm ground and used with fall protection.',
          'Anyone who employs or engages workers to use an Item is responsible for their training, supervision, safety and insurance.',
        ],
      },
      { heading: 'Moving equipment' },
      {
        list: ['Dollies, trolleys, ramps and trailers must be used within their load limits; Users are responsible for injuries from lifting and for damage to goods being moved.'],
      },
      { heading: 'Farming equipment' },
      {
        list: [
          'Farm machinery is dangerous - never wear loose clothing near moving parts, never carry passengers on machines not designed for them, and switch off and remove the key before clearing blockages.',
          'Sprayers and similar Items must be returned cleaned of all chemical residue. The Renter is responsible for complying with the Insecticides Act, 1968 and label directions for any chemicals they use, and for any damage to crops, land, water or animals.',
        ],
      },
    ],
  },
  {
    id: 'damage-loss-theft',
    title: 'Damage, loss and theft during a Rental',
    body: [
      'Unless the Owner and Renter agree otherwise in writing in the Chat, the Renter is responsible for the Item from the moment they take possession of it until the Owner takes it back, and must pay the Owner for any loss, theft or damage (other than fair wear and tear, or a defect that existed before pickup) during that period.',
      {
        list: [
          'Report any damage, accident, breakdown, loss or theft to the Owner immediately, and report theft or any accident involving injury to the police - keep a copy of the complaint or FIR.',
          'The amount payable should be the reasonable cost of repair or, if the Item cannot be repaired or is lost, its fair market value at the time - not the price of a new Item - unless a different amount was agreed.',
          'The Owner must provide reasonable evidence of the damage and its cost.',
          'Rent It does not assess, value, pay for or guarantee any claim.',
        ],
      },
    ],
  },
  {
    id: 'insurance',
    title: 'Insurance',
    body: [
      'Rent It does not provide any insurance of any kind - not for Items, damage, theft, injury, death, third-party liability or loss of income. No part of the Platform should be understood as insurance or a guarantee.',
      'Owners should check whether their own insurance covers renting their Items to others (many policies exclude it) and obtain suitable cover. Renters should consider whether they need liability or personal-accident cover for the work they plan to do. Users bear any loss that is not insured.',
    ],
  },
  {
    id: 'user-disputes',
    title: 'Disputes between Users and our dispute process',
    body: [
      'Disputes about a Rental - including about payment, the Deposit, the condition of an Item, damage, late return or cancellation - are between the Owner and the Renter. We encourage you to resolve them politely and directly first.',
      'Either User may use "Report a problem" on an approved Rental. This freezes the Rental on the Platform while Staff review it. Staff may look at the Rental record, the Offers and the agreed Deal, condition photos, and the Chat between the two Users (including photos, documents and locations sent in it), and may ask either User for more information.',
      'Staff may then mark the Rental as completed or cancelled on the Platform, and may take action on either User\'s account. That decision:',
      {
        list: [
          'is an administrative decision about the Platform only - it is not a judgment, arbitration award or legally binding determination of the Users\' rights against each other;',
          'does not move, refund or recover any money, because Rent It never holds any;',
          'does not stop either User from pursuing any remedy they have under Applicable Law, including before a consumer commission, civil court or the police.',
        ],
      },
      'You agree to cooperate honestly with any review, and not to submit false or edited evidence. We are not obliged to resolve any dispute, and we are not liable for the outcome of any dispute between Users.',
    ],
  },
  {
    id: 'chat',
    title: 'Messaging, photos, documents and locations',
    body: [
      'The Chat lets Owners and Renters discuss and arrange Rentals. You can send text, make and respond to Offers, and - through the "+" menu - send photos (including from your camera), documents (such as PDF or Word rental agreements, receipts or manuals) and locations.',
      {
        list: [
          'Use the Chat only to arrange genuine Rentals. Do not send spam, advertising, chain messages, or anything prohibited by these Terms.',
          'Messages and attachments you send are stored on the Platform and are visible to the other User in that conversation. They may also be accessed by Staff to investigate a report, review a dispute, keep the Platform safe, enforce these Terms or comply with the law. Do not treat the Chat as private from us.',
          'Only share personal information that is necessary. Do not send full identity numbers (for example an unmasked Aadhaar number), bank passwords, OTPs, UPI PINs or card details to anyone.',
          'Photos can contain hidden information, such as where they were taken. Check before sending.',
          'Rent It does not scan attachments for viruses or malware. Open documents only from people you trust, and keep your device\'s security software up to date.',
          'Do not send or share anything you do not have the right to share, including other people\'s documents, photos or personal information without their consent.',
          'Documents such as rental agreements that Users exchange are prepared and agreed by the Users themselves. Rent It does not draft, check, stamp, register or approve them, and is not a party to them.',
        ],
      },
    ],
  },
  {
    id: 'location-and-meetups',
    title: 'Sharing your location and meeting in person',
    body: [
      'You can choose to send your current location, or any place you pick on a map, in the Chat - for example a pickup point. A location is only ever sent when you choose to send it; we do not track your location in the background. Sending your current location uses your device\'s location service and requires your browser\'s permission.',
      'Once sent, a location is visible to the other User and stored with the conversation. Only share a location with someone you are comfortable with, and consider sharing a nearby public place rather than your home.',
      { heading: 'Meeting safely' },
      {
        list: [
          'Meet in a public, well-lit place where possible, preferably in daylight.',
          'Tell a friend or family member where you are going and whom you are meeting, and consider bringing someone with you, especially for high-value or heavy Items.',
          'Check the other person\'s name against their Rent It profile, and trust your instincts - leave if anything feels wrong.',
          'Never hand over an Item or money until you are satisfied, and never share OTPs or PINs.',
          'In an emergency, call 112.',
        ],
      },
      'Rent It does not screen Users for criminal records and is not responsible for the conduct of any User, or for anything that happens when Users meet, whether or not the meeting was arranged through the Platform.',
    ],
  },
  {
    id: 'your-content',
    title: 'Your Content and the licence you give us',
    body: [
      'You keep ownership of the Content you create. By posting, uploading or sending Content on the Platform, you grant Rent It a non-exclusive, royalty-free, worldwide, transferable and sub-licensable licence to host, store, reproduce, display, adapt (for example resizing photos), transmit and otherwise use that Content for the purposes of operating, securing, improving and promoting the Platform and the Listing concerned, and for complying with the law. This licence ends when the Content is deleted from the Platform, except for copies we must keep for legal, safety or dispute-resolution reasons, or that others have already saved.',
      'You represent and warrant that you own or have all rights needed to post your Content and to grant this licence, that your Content is accurate and lawful, and that it does not infringe anyone\'s rights, including privacy and intellectual-property rights.',
      'We do not pre-screen Content and are not responsible for it, but we may review, refuse, hide or remove any Content at any time.',
    ],
  },
  {
    id: 'reviews',
    title: 'Reviews and ratings',
    body: [
      'Reviews help other Users decide whom to trust. When you write one, it must be honest, based on your own genuine experience of the Item or User, and must not be misleading. In line with the Consumer Protection Act, 2019 and the Indian Standard on online consumer reviews (IS 19000:2022), you must not:',
      {
        list: [
          'write fake reviews, reviews of your own Listings, or reviews for a Rental that never happened;',
          'offer or accept money, discounts, free Rentals or anything else in exchange for a review, or for changing or removing one;',
          'threaten a negative review to obtain a refund, discount or any other benefit;',
          'post reviews that are defamatory, abusive, discriminatory, or that reveal someone\'s personal information.',
        ],
      },
      'We may flag, hide or remove reviews that appear to break these rules, and we do not accept payment from anyone to remove or alter reviews.',
    ],
  },
  {
    id: 'prohibited-conduct',
    title: 'Prohibited content and conduct',
    body: [
      'As required by Rule 3(1)(b) of the IT Rules, you must not host, display, upload, modify, publish, transmit, store, update or share any information on the Platform that:',
      {
        list: [
          'belongs to another person and to which you do not have any right;',
          'is obscene, pornographic, paedophilic, invasive of another\'s privacy (including bodily privacy), insulting or harassing on the basis of gender, racially or ethnically objectionable, relating to or encouraging money laundering or gambling, or promoting enmity between different groups on the grounds of religion or caste with the intent to incite violence;',
          'is harmful to children;',
          'infringes any patent, trademark, copyright or other proprietary right;',
          'deceives or misleads the recipient about the origin of the message, or knowingly and intentionally communicates any misinformation or information which is patently false and untrue or misleading in nature;',
          'impersonates another person;',
          'threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence, prevents the investigation of any offence, or is insulting to other nations;',
          'contains software viruses or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource;',
          'is patently false and untrue, and is written or published in any form with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person;',
          'violates any law for the time being in force.',
        ],
      },
      'You also must not:',
      {
        list: [
          'harass, threaten, stalk, abuse, intimidate or discriminate against any User, including on the basis of religion, caste, gender, sexual orientation, disability, region or language;',
          'defraud, cheat or attempt to cheat anyone, or use the Platform to plan or commit any crime;',
          'misuse the Offer, Deal, dispute or review features, or make Offers you do not intend to honour;',
          'collect, scrape, harvest or store other Users\' personal information, or use it for anything other than arranging a Rental;',
          'use bots, scrapers, crawlers or automated tools, or interfere with, overload, probe, test the vulnerability of, or bypass any security or access control of the Platform (security researchers should contact us first at {{supportEmail}});',
          'copy, reverse engineer, decompile or create derivative works of the Platform, or use it to build a competing service;',
          'create multiple accounts, or a new account after being suspended, or otherwise evade any restriction we impose;',
          'upload personal documents of someone else, or use the Platform to share intimate, private or sensitive images of anyone.',
        ],
      },
    ],
  },
  {
    id: 'fraud',
    title: 'Fraud and our limited ability to protect you',
    body: [
      'We take steps to reduce fraud - seller verification, recording of agreed Deals, condition photos, reporting tools and account suspensions - but we cannot verify every User, Item, Listing, document or payment, and no platform can remove all risk. You are responsible for your own decisions about whom to deal with.',
      'Report any suspicious User, Listing or message to us immediately. If you have been defrauded, also report it to the police or at cybercrime.gov.in (helpline 1930). We may share information with law enforcement to assist an investigation (see "Law enforcement").',
    ],
  },
  {
    id: 'taxes-compliance',
    title: 'Taxes and your own legal compliance',
    body: [
      'You are solely responsible for complying with all Applicable Law that applies to you, your Items and your Rentals. In particular, Owners are responsible for:',
      {
        list: [
          'determining whether they need to register for, charge and pay Goods and Services Tax on their rentals (which may depend on their aggregate turnover and other factors), and issuing any invoices the law requires;',
          'declaring rental income and paying income tax on it;',
          'holding any trade licence, shop and establishment registration or other local permission their activity requires;',
          'any stamp duty that may apply to a written rental agreement under the stamp law of the relevant State.',
        ],
      },
      'Rent It does not give tax, legal or accounting advice, does not collect or deposit taxes for Users, and is not responsible for any User\'s tax or regulatory obligations.',
    ],
  },
  {
    id: 'ai-assistant',
    title: 'The support assistant (AI)',
    body: [
      'The Help / FAQ page includes an automated support assistant powered by a third-party artificial-intelligence model. Its answers are generated automatically and may be incomplete, out of date or wrong. They are general information only, not legal, financial, tax, medical or safety advice, and they do not change these Terms. Where the assistant and these Terms differ, these Terms apply.',
      'Messages you type to the assistant are sent to the AI provider to generate a reply. Do not share personal, financial or sensitive information with it.',
    ],
  },
  {
    id: 'third-parties',
    title: 'Third-party services and links',
    body: [
      'The Platform relies on third-party services, including (at the time of writing) hosting and database providers, file storage, an email-delivery provider, an identity-verification provider, an error-monitoring service, an AI provider for the support assistant, OpenStreetMap map tiles and place search for locations, and links to Google Maps. When you use features that depend on them, their own terms and privacy policies may also apply.',
      'The Platform may contain links to websites and services we do not control. We are not responsible for their content, availability, security or practices, and a link is not an endorsement.',
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy and your personal data',
    body: [
      'Our Privacy Policy explains what personal data we collect, why, how long we keep it, whom we share it with, and your rights under the Digital Personal Data Protection Act, 2023 and other Applicable Law. It forms part of these Terms, and by accepting these Terms you also confirm that you have read it.',
      'You are responsible for any personal data of other people that you receive through the Platform (for example a name, phone number, address or location shared with you for a Rental). You may use it only to arrange and complete that Rental, must keep it secure, and must not share it or use it for any other purpose.',
    ],
  },
  {
    id: 'communications',
    title: 'Communications from us',
    body: [
      'By using the Platform you agree that we may send you notices and messages electronically - in the Platform, by in-app notification and by email - about your account, your Listings, Offers, Deals, messages, disputes, security, and changes to these Terms. These service communications are part of the Platform and you cannot opt out of them while you have an account. Electronic notices satisfy any legal requirement for written notice.',
      'We will only send you promotional messages where the law allows, and you can opt out of them at any time.',
    ],
  },
  {
    id: 'our-ip',
    title: 'Our intellectual property',
    body: [
      'The Platform, including its software, design, layout, text, graphics, logos, the "Rent It" name and brand, and all content we create (but not Users\' Content) belongs to us or our licensors and is protected by the Copyright Act, 1957, the Trade Marks Act, 1999 and other laws. We grant you a limited, personal, non-exclusive, non-transferable, revocable licence to use the Platform for its intended purpose in accordance with these Terms. You may not copy, modify, distribute, sell or exploit any part of it without our written permission.',
      'If you send us feedback or suggestions, we may use them freely without any obligation to you.',
    ],
  },
  {
    id: 'ip-complaints',
    title: 'Reporting infringement and unlawful content',
    body: [
      'If you believe Content on the Platform infringes your copyright, trademark or other rights, or is otherwise unlawful, contact our Grievance Officer (see "Grievance redressal") with: your name and contact details; a description of the right or law concerned; a link to or clear identification of the Content; why you believe it is infringing or unlawful; and a statement that the information you provide is true. Where you act for someone else, say so and show your authority.',
      'We will act on valid complaints and on orders of a court or an authorised government agency in accordance with the IT Rules, including by removing or disabling access to the Content within the time required.',
    ],
  },
  {
    id: 'suspension',
    title: 'Suspension, termination and deleting your account',
    body: [
      'We may, with or without notice, restrict features, hide Content, suspend or permanently close your account, or refuse you access to the Platform if: you breach these Terms or Applicable Law; you provide false information; we suspect fraud, abuse, a safety risk or a security threat; we are required to by law or by an authority; or your account has been inactive for a long time. Where appropriate and lawful, we will tell you why.',
      'You may stop using the Platform at any time and may ask us to delete your account. Closing an account does not cancel obligations under Deals already formed (for example returning an Item or paying for a Rental), which you must still honour. Some information may be retained after closure as described in our Privacy Policy - including, as required by Rule 3(1)(h) of the IT Rules, information collected for registration, for 180 days after an account is cancelled or withdrawn.',
    ],
  },
  {
    id: 'availability',
    title: 'Availability and changes to the Platform',
    body: [
      'We may change, add or remove features of the Platform, or suspend or discontinue it in whole or part, at any time. The Platform may be unavailable from time to time, including for maintenance, and may contain errors. We do not guarantee that it will be uninterrupted, timely, secure, error-free or free of viruses, or that any information, message, file or record will be kept or delivered. Keep your own copies of anything important, such as agreements and receipts.',
    ],
  },
  {
    id: 'disclaimers',
    title: 'Disclaimers',
    body: [
      'To the maximum extent permitted by Applicable Law, the Platform and all Content, Listings and information on it are provided "as is" and "as available", without any warranty or representation of any kind, express or implied - including any warranty of merchantability, quality, fitness for a particular purpose, safety, accuracy, availability, title or non-infringement.',
      'We make no warranty or representation about any Item, User, Listing, Deal, payment, document or location, or about the results of using the Platform. Any Item you rent is provided by its Owner, not by us, and any warranty or promise about it is given, if at all, by the Owner alone.',
    ],
  },
  {
    id: 'liability',
    title: 'Limitation of liability',
    body: [
      'To the maximum extent permitted by Applicable Law:',
      {
        list: [
          'Rent It, its directors, officers, employees, agents and service providers will not be liable for any indirect, incidental, special, consequential, exemplary or punitive loss or damage, or for any loss of profit, revenue, business, goodwill, data or opportunity, however caused and even if we were told it might happen;',
          'Rent It will not be liable for any loss, damage, injury, illness or death arising from or connected with any Item, any Rental, any payment or Deposit between Users, any meeting between Users, the conduct or Content of any User, the use of any shared document or location, or any dispute between Users;',
          'our total aggregate liability to you for all claims arising out of or relating to these Terms or the Platform, of whatever nature, will not exceed the greater of (a) the total fees you paid to Rent It in the twelve months before the event giving rise to the claim, and (b) one thousand Indian Rupees (₹1,000).',
        ],
      },
      'Nothing in these Terms excludes or limits any liability that cannot be excluded or limited under Applicable Law, including liability for fraud, or for death or personal injury caused by our own negligence, or your rights as a consumer under the Consumer Protection Act, 2019 to the extent they cannot be waived.',
    ],
  },
  {
    id: 'indemnity',
    title: 'Your indemnity to us',
    body: [
      'You agree to defend, indemnify and hold harmless Rent It and its directors, officers, employees, agents and service providers from and against any and all claims, demands, proceedings, losses, liabilities, damages, penalties, fines, costs and expenses (including reasonable legal fees) arising out of or relating to: your use of the Platform; your Content; any Item you list, rent, transport or use; any Rental, Deal, payment or Deposit you are party to; any injury, death, loss or damage caused by you or by an Item while in your possession; your breach of these Terms; or your violation of any law or of any right of a third party.',
    ],
  },
  {
    id: 'release',
    title: 'Release',
    body: [
      'Because Rent It is not a party to Rentals between Users, you release Rent It and its directors, officers, employees and agents from all claims, demands and damages of every kind, known and unknown, arising out of or in any way connected with any dispute between you and another User, to the maximum extent permitted by Applicable Law.',
    ],
  },
  {
    id: 'force-majeure',
    title: 'Events beyond our control',
    body: [
      'We are not liable for any failure or delay in providing the Platform caused by events beyond our reasonable control, including natural disasters, epidemics, fire, flood, war, terrorism, riots, strikes, government action, internet or power failures, cyber-attacks, or the failure of a third-party service provider.',
    ],
  },
  {
    id: 'governing-law',
    title: 'Governing law and disputes with Rent It',
    body: [
      'These Terms and any dispute or claim arising out of or in connection with them or the Platform are governed by the laws of India.',
      'If you have a dispute with Rent It (not with another User), please first contact our Grievance Officer so we can try to resolve it informally. If it is not resolved within 30 days, it will be referred to and finally resolved by arbitration under the Arbitration and Conciliation Act, 1996, by a sole arbitrator appointed by mutual agreement (or, failing agreement, in accordance with that Act). The seat and venue of arbitration will be {{arbitrationSeat}}, and the proceedings will be conducted in English.',
      'Subject to the arbitration clause, the courts at {{jurisdictionCity}} will have exclusive jurisdiction, including for interim relief. Nothing in this section limits any right you may have as a consumer to approach a Consumer Disputes Redressal Commission under the Consumer Protection Act, 2019, or any other forum that the law does not allow to be excluded.',
    ],
  },
  {
    id: 'grievances',
    title: 'Grievance redressal',
    body: [
      'In accordance with the Information Technology Act, 2000, the IT Rules and the Consumer Protection (E-Commerce) Rules, 2020, the details of our Grievance Officer are:',
      {
        list: [
          'Name: {{grievanceOfficer}}',
          'Email: {{grievanceEmail}}',
          'Phone: {{grievancePhone}}',
          'Address: {{address}}',
          'Available: {{grievanceHours}}',
        ],
      },
      'You may contact the Grievance Officer about any complaint regarding the Platform, its Content, a breach of these Terms, or the handling of your personal data. Please include your name, contact details, a description of the complaint, and links to or identification of any Content concerned. We will acknowledge your complaint within 24 hours and resolve it within 15 days of receipt (or sooner where the law requires, including within 72 hours for certain requests from authorities and within 24 hours for complaints about content that exposes a person\'s private areas, shows them in full or partial nudity or a sexual act, or is an impersonation, including morphed images). We will give you a complaint reference so you can track it.',
      'If you are not satisfied with the Grievance Officer\'s decision, you may appeal to the Grievance Appellate Committee constituted under the IT Rules within 30 days of receiving it.',
    ],
  },
  {
    id: 'law-enforcement',
    title: 'Law enforcement and preserving records',
    body: [
      'We cooperate with law enforcement and government agencies as required by Applicable Law. We may preserve and disclose any information about you, your account, your Listings, Rentals, Offers, Chats and attachments, including personal data, where we believe in good faith that it is required by law or a valid order, or is necessary to prevent or investigate fraud or crime, to protect the safety of any person, or to protect the rights and property of Rent It or its Users. Where required, we will preserve information and records relating to unlawful content or activity for the period the law specifies (currently at least 180 days under the IT Rules, or longer if a court or authority requires).',
    ],
  },
  {
    id: 'changes',
    title: 'Changes to these Terms',
    body: [
      'We may update these Terms from time to time - for example because of new features, new risks, or changes in the law. The "Last updated" date and version at the top show when they last changed. If we make a material change, we will ask you to review and accept the new version when you next open the Platform, and you will not be able to continue using it unless you accept. If you do not agree to the changes, you must stop using the Platform and may close your account.',
    ],
  },
  {
    id: 'general',
    title: 'General',
    body: [
      {
        list: [
          'Entire agreement: these Terms, together with the Privacy Policy and any rules we publish on the Platform, are the entire agreement between you and Rent It about the Platform.',
          'Severability: if any provision is found invalid or unenforceable, it will be enforced to the maximum extent possible and the rest of these Terms will remain in full force.',
          'No waiver: if we do not enforce a provision, that is not a waiver of our right to enforce it later.',
          'Assignment: you may not assign or transfer your rights or obligations under these Terms. We may assign ours, for example as part of a merger, acquisition or sale of assets.',
          'Relationship: nothing in these Terms creates any partnership, joint venture, agency, franchise or employment relationship between you and Rent It.',
          'Survival: the sections on Owners\' and Renters\' responsibilities, payments, deposits, damage, insurance, disclaimers, limitation of liability, indemnity, release, governing law and any others that by their nature should survive will continue after your use of the Platform ends.',
          'Language: these Terms are written in English. If they are translated, the English version prevails.',
          'Headings are for convenience only and do not affect interpretation. "Including" means "including without limitation".',
        ],
      },
    ],
  },
  {
    id: 'contact',
    title: 'Contact us',
    body: [
      'Questions about these Terms? Email {{supportEmail}}, write to {{legalName}}, {{address}}, or use the Help / FAQ page. For complaints, contact the Grievance Officer as described above.',
    ],
  },
];
